version: '3'

services:
  db:
    image: postgres:10
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 80:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db